# Generated by Django 4.2.6 on 2024-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrainfo",
            name="contact_no",
            field=models.CharField(max_length=10),
        ),
    ]
