# Generated by Django 4.2.6 on 2024-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.TextField(),
        ),
    ]
