# Generated by Django 4.2.6 on 2024-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_contact_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default="", max_length=50)),
                ("category", models.CharField(default="", max_length=50)),
                ("subcategory", models.CharField(default="", max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("desc", models.CharField(max_length=300)),
                ("image", models.ImageField(default="", upload_to="shop/images")),
            ],
        ),
    ]
