# Generated by Django 4.2.6 on 2024-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_product_category_subcategory_alter_products_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="products",
            name="subcategory",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.DeleteModel(
            name="Product_category",
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
