# Generated by Django 4.2.6 on 2024-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrainfo",
            name="country",
            field=models.CharField(default="India", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extrainfo",
            name="state",
            field=models.CharField(default="lucknow", max_length=500),
            preserve_default=False,
        ),
    ]
