# Generated by Django 4.2.6 on 2024-11-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_extrainfo_country_extrainfo_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrainfo",
            name="zip",
            field=models.IntegerField(default=0),
        ),
    ]
