# Generated by Django 4.2.6 on 2024-11-22 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_cart_user_user_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_orders",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
