# Generated by Django 4.2.6 on 2024-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
