# Generated by Django 4.2.6 on 2024-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_orderitem_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="total",
        ),
        migrations.AddField(
            model_name="user_orders",
            name="total",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
