# Generated by Django 4.2.6 on 2024-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_remove_orderitem_total_user_orders_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_orders",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
