# Generated by Django 4.2.6 on 2024-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_user_orders_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_orders",
            name="delivered_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
